### ISSUE TITLE
Help victims of dictatorship instead

### ISSUE THREAD

**Issue by fyodoriv** [OB42/RussianBlocker#2]
Reported. This repository is clearly aimed at discriminating the whole nation of Russians who are a victim of dictatorship as much as Ukrainians are.

I know what I’m talking about: I’m Russian who has been protesting for 10 years. That resulted in nothing. If I keep protesting I’ll get in jail until I’m close to my pension. I don’t desire to sacrifice my life for nothing.

The fact that you think that Russians need a push to protest demonstrates that you’re a naive entitled person who was lucky enough to never face a dictatorship.

All Russians I know are against war. We can’t do shit and we feel hopeless as fuck.

I wish you all the best, but please cut this bullshit. Support Ukraine instead.

**Comment by OB42** [comment]
This is for technical issues only.
